version: '3'
services:
  mongodb:
    image: mongo:bionic
    environment:
    - MONGO_INIT_DATABASE=data_deduplication
    ports:
    - 27017:27017
  app:
    build: .
    expose:
    - 8080
    ports:
    - 8080:8080
    depends_on:
    - mongodb
    volumes:
    - ./metrics/blocks:/tmp
    environment:
    - PORT=8080
    - BLOCK_SIZE=256
    - HASH_TYPE=SHA-256
    - BASE_PATH=/tmp
    - DB_URI=mongodb://mongodb:27017/data_deduplication
