version: '3'
services:
  mongodb:
    image: mongo:bionic
    environment:
      - MONGO_INIT_DATABASE=data_deduplication
    ports:
      - "27017:27017"
  app:
    build: .
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - ./metrics/blocks:/data
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - DB_URI=mongodb://mongodb:27017/data_deduplication
      - HASH_TYPE=SHA-256
      - BLOCK_SIZE=32768
      - BASE_PATH=/data
