server:
  port: ${PORT}
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: ${DB_URI}
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

storage:
  blockSize: ${BLOCK_SIZE}
  basePath: ${BASE_PATH}
  hashType: ${HASH_TYPE}

