server:
  port: ${PORT}
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: ${DB_URI}

storage:
  blockSize: ${BLOCK_SIZE}
  basePath: ${BASE_PATH}
  hashType: ${HASH_TYPE}

