data:
  need_create: true
  path: test_data
  size: 2 GB
  min_change_size: 1 MB
  max_change_size: 10 MB
  min_file_size: 30 MB
  max_file_size: 40 MB
  min_change_blocks: 1
  max_change_blocks: 10
  remove_shance_percentage: 10

block:
  min_size: 512 B
  max_size: 64 KB
  denominator: 2
  hash_functions:
    - SHA-256
    - MURMUR3-128

project:
  path: ../
  api_url: http://localhost:8080/api
  storage_path: /storage

result:
  plots_path: plots
  data_path: saved_data
